version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
        
      - run: lein test
      - attach_workspace:
          at: ~/
      - run: lein uberjar
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  dockerize:
     working_directory: ~/repo
     machine: true
     steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -f deploy/backend/Dockerfile -t falcowinkler/tweetbird:$CIRCLE_BRANCH .
      - run: docker push falcowinkler/tweetbird:$CIRCLE_BRANCH



workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build